language: bash
services: docker

branches:
  except:
    - /dist.*/

env:
  - VERSION=glibc
  - VERSION=musl
  - VERSION=uclibc

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - image="busybox:$VERSION"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      ./build.sh "$VERSION"
      docker build -t "$image" "$VERSION"
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
